apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname
spec:
  selector:
    matchLabels:
      app: hostname
  replicas: 2
  template:
    metadata:
      labels:
        app: hostname
    spec:
      containers:
      - name: hostname
        image: mirrorgooglecontainers/serve_hostname
        ports:
        - containerPort: 9376
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hostname
spec:
  selector:
    app: hostname
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 9376
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostname
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /web
        backend:
          service:
            name: hostname
            port:
              number: 80
