apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitor
spec:
  type: NodePort
  externalIPs:
    - 192.168.1.30
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
